### ISSUE TITLE
`chronicle_rsm:record_delayed_reply()` must handle `not_found` return from `find_peer_state`

### ISSUE THREAD

**Issue by aartamonau** [couchbase/chronicle#6]
`record_delayed_reply()` is part of special handling added specifically for `chronicle_config_rsm`. `find_peer_state` will return `not_found` when the peer that submitted the request is not part of the topology anymore.

Running the following in a remote shell kills `chronicle` on all nodes:

```
(chronicle_1@127.0.0.1)1> spawn(fun () -> chronicle:remove_peer(node()) end), spawn(fun () -> chronicle:remove_peer(node()) end).
<0.205.0>
(chronicle_1@127.0.0.1)2> chronicle_kv:*** ERROR: Shell process terminated! (^G to start new job) ***
```

The stacktrace looks like this:

```
** Reason for termination = error:{case_clause,not_found}
** Callback modules = [chronicle_rsm]
** Callback mode = handle_event_function
** Stacktrace =
**  [{chronicle_rsm,record_delayed_reply,3,
                    [{file,"/home/shaleny/dev/chronicle/src/chronicle_rsm.erl"},
                     {line,870}]},
     {lists,foldl,3,[{file,"lists.erl"},{line,1350}]},
     {chronicle_rsm,apply_entry,2,
                    [{file,"/home/shaleny/dev/chronicle/src/chronicle_rsm.erl"},
                     {line,1156}]},
     {lists,foldl_1,3,[{file,"lists.erl"},{line,1355}]},
     {chronicle_rsm,apply_entries,4,
                    [{file,"/home/shaleny/dev/chronicle/src/chronicle_rsm.erl"},
                     {line,1108}]},
     {chronicle_rsm,handle_seqno_committed,3,
                    [{file,"/home/shaleny/dev/chronicle/src/chronicle_rsm.erl"},
                     {line,1335}]},
     {gen_statem,loop_state_callback,11,[{file,"gen_statem.erl"},{line,1428}]},
     {proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,240}]}]
```
The simplest fix would be to handle `not_found` in the same way `stale` is handled. This will protect against the crash. But note that this is, strictly speaking, not a backwards compatible change. But given that the consequences of the old "behavior" are catastrophic, it's probably ok.

Separately, `chronicle_config_rsm` probably shouldn't accept config changes from removed peers (regular state machine commands from removed peers are rejected). But that a bigger change.

**Comment by anuthan** [comment]
Thanks for reporting the issue @aartamonau
